export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_CHUCK = 'FETCH_CHUCK';
export const FETCH_BEST_MOVIES_2018 = 'FETCH_BEST_MOVIES_2018';
export const IS_LOADING_WEATHER = 'IS_LOADING_WEATHER';
export const IS_LOADING_CHUCK = 'IS_LOADING';