export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_CHUCK = 'FETCH_CHUCK';
export const FETCH_BEST_MOVIES_2018 = 'FETCH_BEST_MOVIES_2018';
export const FETCH_HIGHEST_RATED_MOVIES = 'FETCH_HIGHEST_RATED_MOVIES';
export const FETCH_MOST_POPULAR_MOVIES = 'FETCH_MOST_POPULAR_MOVIES';

export const IS_LOADING_WEATHER = 'IS_LOADING_WEATHER';
export const IS_LOADING_CHUCK = 'IS_LOADING_CHUCK';
export const IS_LOADING_MOVIE = 'IS_LOADING_MOVIE';

export const FETCH_YOUTUBE_MOVIE = 'FETCH_YOUTUBE_MOVIE';

export const ACTIVATE_OVERLAY = 'ACTIVATE_OVERLAY';

