export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_CHUCK = "FETCH_CHUCK";

export const IS_LOADING_WEATHER = "IS_LOADING_WEATHER";
export const IS_LOADING_CHUCK = "IS_LOADING_CHUCK";
export const IS_LOADING_MOVIE = "IS_LOADING_MOVIE";

export const FETCH_YOUTUBE_MOVIE_START = "FETCH_YOUTUBE_MOVIE_START";
export const FETCH_YOUTUBE_MOVIE_SUCCESS = "FETCH_YOUTUBE_MOVIE_SUCCESS";
export const FETCH_YOUTUBE_MOVIE_FAILURE = "FETCH_YOUTUBE_MOVIE_FAILURE";

export const ACTIVATE_OVERLAY = "ACTIVATE_OVERLAY";
export const UPDATE_VIEW = "UPDATE_VIEW";

export const FETCH_MOVIE_START = "FETCH_MOVIE_START";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";
